apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: odc-db-creation-
spec:
  entrypoint: odc-db-creation
  podGC:
    strategy: OnWorkflowSuccess
  templates:
    - name: odc-db-creation
      script:
        image: ghcr.io/digitalearthpacific/datacube-ows:0.0.1-68-gb3a9612
        resources:
          requests:
            memory: 500Mi
            cpu: 1000m
        command: [bash]
        source: |
          # Author: Alex Leith
          # Date: 2024-10-04

          set -xe

          NEW_DB=$USER

          # Export ODC Connection info. PGUSER and PGPASSWORD are superadmin credentials
          export ODC_DEFAULT_DB_URL=postgresql://$PGUSER:$PGPASSWORD@$PGHOST:5432/$NEW_DB
          export ODC_DEFAULT_INDEX_DRIVER=postgis

          # Initialise the ODC and OWS schemas
          datacube spindex create 3857
          # psql -d $NEW_DB -c "UPDATE odc.alembic_version SET version_num='d27eed82e1f6' WHERE odc.alembic_version.version_num = '610f32dca3cb'"

        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: db-admin
                key: postgres-password
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: db-admin
                key: postgres-username
          - name: PGHOST
            value: "db-endpoint.db.svc.cluster.local"
          - name: PGDATABASE
            value: dep
          - name: USER
            valueFrom:
              secretKeyRef:
                name: odc
                key: username
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: odc
                key: password
          - name: READUSER
            valueFrom:
              secretKeyRef:
                name: odcread
                key: username
          - name: READPASS
            valueFrom:
              secretKeyRef:
                name: odcread
                key: password
